name: Build project
on:
  # Build on pushes to that have a version tag
  push:
    tags:
      - v*
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
  ITCH_GAME: family-tree
  ITCH_USER: william-ritson

jobs:
  buildForSomePlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - .
        unityVersion:
          - 2020.3.15f2
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64  # Build a Linux 64-bit standalone.
          - WebGL # WebGL
    steps:
      # Checkout
      - uses: actions/checkout@v2
        with:
          lfs: true
      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
      # Build
      - uses: game-ci/unity-builder@v2
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
      # Upload
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build

  deployToItch:
    name: Deploy game to itch.io
    runs-on: ubuntu-latest
    needs: [buildForSomePlatforms]
    steps:
      - name: Download build
        uses: actions/download-artifact@v4.1.7
        with:
          name: Build
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          CHANNEL: windows-x64
          PACKAGE: Build/StandaloneWindows64
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          CHANNEL: osx
          PACKAGE: Build/StandaloneOSX
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          CHANNEL: linux
          PACKAGE: Build/StandaloneLinux64
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          CHANNEL: web
          PACKAGE: Build/WebGL
      # Delete the artifact after we upload it to itch.io
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: Build
